### ISSUE TITLE
Compose TiltSerie tasks

### ISSUE THREAD

**Issue by albertmena** [scipion-em/scipion-em-tomo#327]
- [x] Add spherical aberration to each tilt 
- [x] Empty set on TiltSerie summary, is the spherical aberration?
![Screenshot from 2023-03-06 13-10-30](https://user-images.githubusercontent.com/12760268/223106775-ecbeb238-5d1f-45ce-9abd-669b8bb995ea.png)
- [ ] Replace the time4NextTilt parameter for a reading of a temporary file named “nombretiltSerie".rawtlt, when the tiltserie is finished the file is removed
- [x] Adjust the id count setObjId
- [x] Add a nameTS.rawtlt with the list of all tilts angles, to help imod import TS

**Comment by Vilax** [comment]
The empty set symbol represents that the set lacks of associated transformation matrix. It means, the set of titl series do not have the alignment information. 
In my opinion the spherical aberration should only be stored int he Sqlite, but not in the object tilt series. In fact, the set of tilt series have access should have access to the spherical aberration because the class set of tilt series inherits from the class EMObject.

**Comment by albertmena** [comment]
Improvements
https://github.com/scipion-em/scipion-em-tomo/pull/351
