### ISSUE TITLE
Allow tomo to mics to make an averge

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-tomo#377]
https://github.com/scipion-em/scipion-em-tomo/blob/devel/tomo/protocols/protocol_tomo_to_mics.py

Add a parameter to ask for averaging slices.

**Comment by Vilax** [comment]
I would add sum, not only average, otherwise, the depth information is lost and later steps like a reconstruction would not behave properly.

**Comment by JorMaister** [comment]
Indeed, we're performing the sum, not the average. @Vilax , is the average useful? Should it be included?

**Comment by Vilax** [comment]
I comment about the average, because I read the title of the issue. I didn't know you pretend to to do a sum. In that case, nothing to add

**Comment by JorMaister** [comment]
Hi @Vilax! I think it has been a language misunderstanding. Sorry, our fault! Here is what the protocol offers:

![image](https://github.com/scipion-em/scipion-em-tomo/assets/54907551/94df4dee-aeb3-4f87-8303-a8f3138b19c3)

If you think that a slice averaging mode should be added (now I'm confused haha), please let us know.

**Comment by Vilax** [comment]
Yes, it was a misunderstanding. 

About adding an averaging... I think it is not neccesary.

In the case of computing the sum. I would set slices gap = 1. And I would add two parameters. First slice and last slice. Because if we skip slices, then the depth is lost

Sorry, for comment on this, I did not pretend to do it. I just went to see the issue about the tlt files, and I saw the title of this, then I felt curiosity because of the title. I know this is out of my duties
